os:
  - linx
  - osx

language: c
sudo: required

env:
  matrix:
    - CONDA_PY=2.6
    - CONDA_PY=2.7
    - CONDA_PY=3.3
    - CONDA_PY=3.4
    - CONDA_PY=3.5

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./run_tests_travis.sh
